fixed duplicate entries issue
BITSoC/A-POP pull request #5
Opened 2020-08-04 22:42 UTC by viditchopra1500

Now if somebody adds a song already in the list then an alert dialog box will appear with the message "the song is already in the list"

2020-08-06 03:01 UTC, abhisheknaiidu requested changes
Good, but one suggestion why not we show the dialog box, just after clicking the `ADD` rather than clicking on `ADD SONG` , It will make better User Experience.

2020-08-06 03:49 UTC, viditchopra1500 commented
Now the dialog box appears after clicking ADD

2020-08-06 17:50 UTC, abhisheknaiidu requested changes
Looks Great, but could you use this package for alerts, it will improve the interface greatly.

https://github.com/t4t5/sweetalert

2020-08-06 17:50 UTC, abhisheknaiidu commented on src/components/AddSong.js
> +
Remove this extra `line-space`

2020-08-06 17:50 UTC, abhisheknaiidu commented on src/components/AddSong.js
> +        var flag=0
Change `var` to es6 variables `const` or `let`

2020-08-06 21:54 UTC, abhisheknaiidu requested changes
I tried to make small changes and commit in you're PR, but not able to make it, because of `forked` repo maybe

2020-08-06 21:54 UTC, abhisheknaiidu commented on package.json
>      "subscriptions-transport-ws": "^0.9.16"
Add `,` in the last, it's giving error

2020-08-06 21:54 UTC, abhisheknaiidu commented on src/components/AddSong.js
> +        flag===1?swal('Song already present in list!!'):showDialog(true)
change it to `swal("Oops" ,  "Song is already present in list!!" ,  "error")`

2020-08-07 09:29 UTC, abhisheknaiidu approved these changes
Great!

2020-08-07 09:29 UTC, merged